server:
  port: 8089
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: login
  config:
    import:
      optional:file:env.properties
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/order_bridge_login?serverTimezone=Asia/Seoul
    username: login
    password: login
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: info
    org.springframework.web: info
    com.zaxxer.hikari: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    jdbc.connection: info

token:
  secret: ${TOKEN}
  expiration_time: 43200000

frontend: http://localhost:5174