server:
  port: 8070
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: login
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/order_bridge_login?serverTimezone=Asia/Seoul
    username: login
    password: login
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

springdoc:
  packages-to-scan: error.pirate.backend
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    operations-sorter: method
    doc-expansion: none

logging:
  level:
    root: info
    org.springframework.web: info
    com.zaxxer.hikari: info
    log4jdbc.log4j2: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    jdbc.connection: info
